// <auto-generated />
namespace SmartBILL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addPartyChallanItemsRelItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addPartyChallanItemsRelItems));
        
        string IMigrationMetadata.Id
        {
            get { return "202505031523092_addPartyChallanItemsRelItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
